Do not remove libassuan.
A python lib we use (python-value_key) depends on this. If it fails to
import the module we see weird problems importing python modules backed up
by .so libraries, for instance:

ImportError: /lib64/libcryptsetup.so.1: undefined symbol: uuid_generate

Related: rhbz#684742